// Auto-generated by scripts/fetch-exercise-images.mjs
// To populate: node scripts/fetch-exercise-images.mjs YOUR_RAPIDAPI_KEY
//
// You can also manually add URLs here for any exercise:
//   "k03": "https://v2.exercisedb.io/image/...",
//   "k03": "https://www.youtube.com/watch?v=...",   ← YouTube embed
//   "k03": "https://example.com/my-clip.mp4",       ← direct video
//   "k03": "https://example.com/image.gif",         ← any image/gif
//
// Supported URL types (auto-detected by the app):
//   • v2.exercisedb.io or any image/gif URL  → <img> tag
//   • youtube.com / youtu.be                 → <iframe> embed
//   • .mp4 / .webm                           → <video> player

export default {
  // ── populated by running the fetch script ──
};
